const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./app']
// const endpointsFiles = ['./endpoints.js']

// swaggerAutogen(outputFile, endpointsFiles)
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Employee",
            "description": "Endpoints"
        }
    ],
    // securityDefinitions: {
    //     api_key: {
    //         type: "apiKey",
    //         name: "api_key",
    //         in: "header"
    //     },
    //     petstore_auth: {
    //         type: "oauth2",
    //         authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
    //         flow: "implicit",
    //         scopes: {
    //             read_pets: "read your pets",
    //             write_pets: "modify pets in your account"
    //         }
    //     }
    // },
    definitions: {
        Employee: {
            empID: 1,
            empName: 'Hamza',
            empDept: 1,
            empCNIC: "1234-1245"

        },
        AddEmployee: {
            $empID: 1,
            empName: "Jhon Doe",
            empDept: 1,
            empCNIC: "1234-1234"
        }
    }
}
swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./app.js')
})